version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
      start_period: 10s

  airflow:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Fernet key valid: 32-byte url-safe base64-encoded
      AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      # Supaya Airflow tahu lokasi DAGs
      AIRFLOW__CORE__DAGS_FOLDER: /app/dags
    volumes:
      - ./dags:/app/dags
      - ./scripts:/app/scripts
      - ./artifacts:/app/artifacts
    ports:
      - "8082:8080"
    command: airflow standalone
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure